#!/bin/bash
#远端文件储存地址
Github="https://ghproxy.com/https://raw.githubusercontent.com/gao1354184430/Gggd/master/test/test6"
GostService="https://raw.githubusercontent.com/KANIKIG/Multi-EasyGost/master"
cndownload="https://ghproxy.com/https://raw.githubusercontent.com/gao1354184430/Gggd/master/test/test5"
#gost指定版本
ct_new_ver="2.11.1"
#测试与GitHub连通性
rm -rf /root/.test.txt
curl -s $Github/test > /root/.test.txt
github_test=`sed -n '1p' /root/.test.txt`
rm -rf /root/.test.txt /root/.crontab.txt
#开放防火墙
function install_iptables(){
systemctl stop firewalld
systemctl mask firewalld
yum install -y iptables
yum install iptables-services -y
iptables -F
iptables -P INPUT ACCEPT
iptables -X
service iptables save
}
#安装vnets
function install_vnets(){
	yum -y install zip unzip vim
    mkdir /usr/local/vnet
    cd /usr/local/vnet
    wget -N --no-check-certificate "https://www.isyunyi.com/download/linux/tunnel.zip"
    unzip tunnel.zip 
    rm -f /usr/local/vnet/tunnel.zip
    rm -f /usr/local/vnet/client
    echo '#!/bin/bash
sleep 0.5
cd /usr/local/vnet
./server' >/usr/local/vnet/server.sh  
	rm -rf /usr/local/vnet/server.conf
	wget -N --no-check-certificate $Github/node/$diQu/server.conf -O /usr/local/vnet/server.conf
    chmod +x /usr/local/vnet/server /usr/local/vnet/server.sh /usr/local/vnet/server.conf
	echo '
[Unit]
Description=VnetServer.Service
After=rc-local.service network.target
[Service]
Type=simple
ExecStart=/usr/local/vnet/server.sh
ExecStartPost=/usr/local/vnet/server.conf
Restart=always
LimitNOFILE=512000
LimitNPROC=512000
[Install]
WantedBy=multi-user.target' >/usr/lib/systemd/system/vnets.service
	systemctl start vnets
	systemctl status vnets
	systemctl enable vnets
	echo -e "\033[42;37mvnet服务端安装完成\033[0m" 
}
#安装docker
function install_docker(){
wget -qO- get.docker.com | bash
systemctl start docker
systemctl enable docker
systemctl status docker
sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
rm -rf /root/docker.run
wget --no-check-certificate $Github/node/$diQu/docker -O /root/docker.run
chmod +x /root/docker.run
/root/docker.run
}
#安装gost
function Install_gost() {
	bit="amd64"
	yum install -y gzip
    rm -rf /root/gost-linux-"$bit"-"$ct_new_ver".gz
    wget --no-check-certificate https://github.com/ginuerzh/gost/releases/download/v$ct_new_ver/gost-linux-$bit-$ct_new_ver.gz -O /root/gost-linux-$bit-$ct_new_ver.gz
    gunzip /root/gost-linux-"$bit"-"$ct_new_ver".gz
    mv /root/gost-linux-"$bit"-"$ct_new_ver" /usr/bin/gost
    chmod -R 777 /usr/bin/gost
    wget --no-check-certificate $GostService/gost.service && chmod -R 777 gost.service && mv gost.service /usr/lib/systemd/system
	rm -rf /etc/gost/config.json
    mkdir /etc/gost && wget --no-check-certificate $Github/node/$diQu/config.json && mv config.json /etc/gost && chmod -R 777 /etc/gost
	systemctl enable gost && systemctl restart gost
	echo "------------------------------"
if test -a /usr/bin/gost -a /usr/lib/systemctl/gost.service -a /etc/gost/config.json; then
    echo "gost安装成功"
    rm -rf "$(pwd)"/gost
    rm -rf "$(pwd)"/gost.service
    rm -rf "$(pwd)"/config.json
else
    echo "gost没有安装成功，可以在Github[EasyGost]中提交issue"
    rm -rf "$(pwd)"/gost
    rm -rf "$(pwd)"/gost.service
    rm -rf "$(pwd)"/config.json
    rm -rf "$(pwd)"/gost.sh
fi
}
#安装nginx1.18
function install_nginx() {
	yum -y update
	rpm -ivh http://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.18.0-2.el7.ngx.x86_64.rpm
	mkdir -p /usr/local/nginx/
	wget $Github/mjnginx.conf -O $nginx_Conf
	#写入配置文件
	cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup
echo "worker_processes  1;
user nobody;
events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    server {
        listen       2333;
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
	include /usr/local/nginx/*.conf;
}">/etc/nginx/nginx.conf
	systemctl resatrt nginx
	systemctl enable nginx
	systemctl status nginx
}
#安装tengine
function install_tengine() {
        yum install epel-release -y
		#创建一个www用户
		useradd -s /sbin/nologin -M www-data
        wget -N -P /usr/sbin/ $cndownload/download/nginx
        chmod +x /usr/sbin/nginx
		wget -N -P /lib/systemd/system/ $cndownload/download/nginx.service
		mkdir /usr/local/nginx
		mkdir /usr/local/nginx/logs
		mkdir /etc/nginx
		mkdir /etc/nginx/conf.d
		wget -N -P /etc/nginx $cndownload/download/nginx.conf
		wget -N -P /etc/nginx https://file.reimucloud.com/bin/tengine/CentOS/mime.types
        wget -N -P /etc/nginx/conf.d https://file.reimucloud.com/bin/nginx_proxy/ws
        wget -N -P /etc/nginx/conf.d https://file.reimucloud.com/bin/nginx_proxy/ssr.stream.sample
        wget -N -P /etc/nginx/conf.d https://file.reimucloud.com/bin/nginx_proxy/v2ray.conf.sample
		mkdir /etc/nginx/modules
		wget -N -P /etc/nginx/modules https://file.reimucloud.com/bin/tengine/CentOS/ngx_stream_module.so
        systemctl start nginx
        systemctl enable nginx
        echo -e "${Green}done!${Font}"
}
#菜单选项
function menu_server() {
  echo && echo -e "  月抛/正常鸡 一键安装docker/vnet/gost
  支持一键安装并从远端下发配置-直接黑化
 ————————————
 ${Green_font_prefix} tw:${Font_color_suffix} 安装至台湾机器
 ${Green_font_prefix} tw2:${Font_color_suffix} 安装至台湾2号机
 ${Green_font_prefix} jp:${Font_color_suffix} 安装至日本机器
————————————
 ${Green_font_prefix} 3.${Font_color_suffix} 安装脚本" &&echo 
	echo -e "输入\033[32m tw\033[0m|\033[32m jp\033[0m来进行安装" 
  echo
  read -erp " 请输入国家地区代码:" diQu
	yum update -y
	install_iptables
	install_docker
	install_vnets
	Install_gost
}
#cn菜单
function menu_server2() {
  echo && echo -e "  国内机器 一键安装Nginx/Brook等
  支持一键安装并从远端下发配置-直接黑化
 ————————————
 ${Green_font_prefix} 1:${Font_color_suffix} 安装Nginx负载
 ${Green_font_prefix} 2:${Font_color_suffix} 安装tengine负载（nginx1.17）
 ${Green_font_prefix} 3:${Font_color_suffix} 没写
————————————
 ${Green_font_prefix} 0.${Font_color_suffix} 安装全部" &&echo 
  echo
  read -erp " 请输入对应的数字:" Num
  case "$Num" in
  1)
    install_nginx
    ;;
  2)
    install_tengine
    ;;
  3)
    echo "说了没写"
    ;;
  0)
    echo "说了没写"
    ;;
  *)
    echo "请输入正确数字 [1-3]"
    ;;
  esac
}
action=$1
if [[ -n $action ]]; then
#增加一个通信检测，如果与GitHub通信失败则停止脚本
	if [[ $github_test == "success" ]]; then
		if [[ $action == "cn" ]]; then
			menu_server2			
		elif [[ $action == "cron" ]]; then
			echo -e "\033[32m 还没写 \033[0m"
		fi
	else
		echo -e "\033[31m 远端通信失败，程序中止 \033[0m"
	fi
else
	menu_server
fi
